Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -9,35 +9,43 @@ jobs:
 
     runs-on: ubuntu-latest
 
-    services:
-      myapp:
-        image: ghcr.io/honeymakhija/cbd3345_ica2/myapp-image:latest
-        ports:
-          - 8080:8080
-        options: --entrypoint "python -m test_app" 
-
+  
     steps:
-    - uses: actions/checkout@v2
-    - name: Set up Python 3.8
-      uses: actions/setup-python@v2
-      with:
-        python-version: 3.8
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
-    - name: Run tests
-      run: |
-        pytest test_app.py
-    - name: Write test results to file
-      run: |
-        if [ $? -eq 0 ]; then
-          echo "All tests passed" > test_file.txt
-        else
-          echo "Tests failed" > test_file.txt
-        fi
-    - name: Archive test file
-      uses: actions/upload-artifact@v2
-      with:
-        name: test-file
-        path: test_file.txt
+      - name: Checkout Repository
+        uses: actions/checkout@v2
+
+      - name: Authenticate with Github
+        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+
+      - name: Pull Docker Image
+        run: docker pull ghcr.io/image:latest
+
+      - name: Run Docker Container with Tests
+        run: |
+          docker run --rm ghcr.io/image:latest
+
+
+      - uses: actions/checkout@v2
+      - name: Set up Python 3.8
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.8
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+      - name: Run tests
+        run: |
+          pytest test_app.py
+      - name: Write test results to file
+        run: |
+          if [ $? -eq 0 ]; then
+            echo "All tests passed" > test_file.txt
+          else
+            echo "Tests failed" > test_file.txt
+          fi
+      - name: Archive test file
+        uses: actions/upload-artifact@v2
+        with:
+          name: test-file
+          path: test_file.txt
